"""baseline: current schema

Revision ID: f0fef8e6007c
Revises: 
Create Date: 2026-06-11 22:07:53.804660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fef8e6007c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynasty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('theme_identifier_or_json', sa.Text(), nullable=False),
    sa.Column('current_wealth', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('current_simulation_year', sa.Integer(), nullable=False),
    sa.Column('founder_person_db_id', sa.Integer(), nullable=True),
    sa.Column('prestige', sa.Integer(), nullable=True),
    sa.Column('infamy', sa.Integer(), nullable=True),
    sa.Column('honor', sa.Integer(), nullable=True),
    sa.Column('piety', sa.Integer(), nullable=True),
    sa.Column('is_ai_controlled', sa.Boolean(), nullable=False),
    sa.Column('ai_personality', sa.String(length=20), nullable=True),
    sa.Column('current_iron', sa.Integer(), nullable=True),
    sa.Column('current_timber', sa.Integer(), nullable=True),
    sa.Column('capital_territory_id', sa.Integer(), nullable=True),
    sa.Column('coat_of_arms_svg', sa.Text(), nullable=True),
    sa.Column('family_tree_svg', sa.Text(), nullable=True),
    sa.Column('is_turn_processing', sa.Boolean(), nullable=False),
    sa.Column('epic_story_text', sa.Text(), nullable=True),
    sa.Column('designated_heir_id', sa.Integer(), nullable=True),
    sa.Column('succession_law', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_played_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capital_territory_id'], ['territory.id'], ),
    sa.ForeignKeyConstraint(['designated_heir_id'], ['person_db.id'], name='fk_dynasty_designated_heir', use_alter=True),
    sa.ForeignKeyConstraint(['founder_person_db_id'], ['person_db.id'], name='fk_dynasty_founder_person', use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dynasty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynasty_name'), ['name'], unique=False)

    op.create_table('person_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('mother_sim_id', sa.Integer(), nullable=True),
    sa.Column('father_sim_id', sa.Integer(), nullable=True),
    sa.Column('spouse_sim_id', sa.Integer(), nullable=True),
    sa.Column('titles_json', sa.Text(), nullable=True),
    sa.Column('traits_json', sa.Text(), nullable=True),
    sa.Column('is_noble', sa.Boolean(), nullable=True),
    sa.Column('is_monarch', sa.Boolean(), nullable=True),
    sa.Column('reign_start_year', sa.Integer(), nullable=True),
    sa.Column('reign_end_year', sa.Integer(), nullable=True),
    sa.Column('is_pretender', sa.Boolean(), nullable=False),
    sa.Column('pretender_strength', sa.Integer(), nullable=False),
    sa.Column('has_seen_majority', sa.Boolean(), nullable=False),
    sa.Column('diplomatic_skill', sa.Integer(), nullable=True),
    sa.Column('military_skill', sa.Integer(), nullable=True),
    sa.Column('stewardship_skill', sa.Integer(), nullable=True),
    sa.Column('espionage_skill', sa.Integer(), nullable=True),
    sa.Column('portrait_svg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['father_sim_id'], ['person_db.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mother_sim_id'], ['person_db.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spouse_sim_id'], ['person_db.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_db', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_db_dynasty_id'), ['dynasty_id'], unique=False)

    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_climate', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_name'), ['name'], unique=False)

    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.Enum('FOOD', 'TIMBER', 'STONE', 'IRON', 'GOLD', 'SPICES', 'WINE', 'SILK', 'JEWELRY', name='resourcetype'), nullable=False),
    sa.Column('base_value', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('perishability', sa.Float(), nullable=True),
    sa.Column('is_luxury', sa.Boolean(), nullable=True),
    sa.Column('scarcity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('territory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('controller_dynasty_id', sa.Integer(), nullable=True),
    sa.Column('governor_id', sa.Integer(), nullable=True),
    sa.Column('is_capital', sa.Boolean(), nullable=True),
    sa.Column('terrain_type', sa.Enum('PLAINS', 'HILLS', 'MOUNTAINS', 'FOREST', 'DESERT', 'TUNDRA', 'COASTAL', 'RIVER', 'LAKE', 'SWAMP', name='terraintype'), nullable=False),
    sa.Column('x_coordinate', sa.Float(), nullable=False),
    sa.Column('y_coordinate', sa.Float(), nullable=False),
    sa.Column('base_tax', sa.Integer(), nullable=True),
    sa.Column('base_manpower', sa.Integer(), nullable=True),
    sa.Column('development_level', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('fortification_level', sa.Integer(), nullable=True),
    sa.Column('is_coastal', sa.Boolean(), nullable=True),
    sa.Column('is_sea', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['controller_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['governor_id'], ['person_db.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territory_controller_dynasty_id'), ['controller_dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_territory_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_territory_province_id'), ['province_id'], unique=False)

    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('army',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.Column('commander_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_sieging', sa.Boolean(), nullable=True),
    sa.Column('created_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commander_id'], ['person_db.id'], ),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('army', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_army_dynasty_id'), ['dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_army_territory_id'), ['territory_id'], unique=False)

    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('building_type', sa.Enum('FARM', 'MINE', 'LUMBER_CAMP', 'WORKSHOP', 'MARKET', 'PORT', 'WAREHOUSE', 'TRADE_POST', 'BARRACKS', 'STABLE', 'TRAINING_GROUND', 'FORTRESS', 'ROADS', 'IRRIGATION', 'GUILD_HALL', 'BANK', name='buildingtype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Float(), nullable=True),
    sa.Column('effects_json', sa.Text(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=False),
    sa.Column('last_upgraded_year', sa.Integer(), nullable=True),
    sa.Column('maintenance_cost', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_territory_id'), ['territory_id'], unique=False)

    op.create_table('chronicle_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['dynasty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claimant_sim_id', sa.Integer(), nullable=False),
    sa.Column('target_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('source_dynasty_id', sa.Integer(), nullable=True),
    sa.Column('claim_type', sa.String(length=30), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('created_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimant_sim_id'], ['person_db.id'], name='fk_claim_claimant', use_alter=True),
    sa.ForeignKeyConstraint(['source_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['target_dynasty_id'], ['dynasty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_claimant_sim_id'), ['claimant_sim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_source_dynasty_id'), ['source_dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_target_dynasty_id'), ['target_dynasty_id'], unique=False)

    op.create_table('diplomatic_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty1_id', sa.Integer(), nullable=False),
    sa.Column('dynasty2_id', sa.Integer(), nullable=False),
    sa.Column('relation_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dynasty1_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['dynasty2_id'], ['dynasty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dynasty1_id', 'dynasty2_id', name='uix_diplomatic_relation')
    )
    with op.batch_alter_table('diplomatic_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diplomatic_relation_dynasty1_id'), ['dynasty1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diplomatic_relation_dynasty2_id'), ['dynasty2_id'], unique=False)

    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty_id', sa.Integer(), nullable=False),
    sa.Column('principal', sa.Integer(), nullable=False),
    sa.Column('amount_owed', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Integer(), nullable=False),
    sa.Column('year_borrowed', sa.Integer(), nullable=False),
    sa.Column('year_repaid', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_dynasty_id'), ['dynasty_id'], unique=False)

    op.create_table('marriage_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposer_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('target_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('proposer_person_id', sa.Integer(), nullable=True),
    sa.Column('target_person_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposer_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['proposer_person_id'], ['person_db.id'], name='fk_marriageoffer_proposer_person', use_alter=True),
    sa.ForeignKeyConstraint(['target_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['target_person_id'], ['person_db.id'], name='fk_marriageoffer_target_person', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marriage_offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marriage_offer_proposer_dynasty_id'), ['proposer_dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marriage_offer_target_dynasty_id'), ['target_dynasty_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty_id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('target_territory_id', sa.Integer(), nullable=True),
    sa.Column('target_dynasty_id', sa.Integer(), nullable=True),
    sa.Column('target_person_id', sa.Integer(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('started_year', sa.Integer(), nullable=False),
    sa.Column('completion_year', sa.Integer(), nullable=False),
    sa.Column('yearly_cost_gold', sa.Integer(), nullable=True),
    sa.Column('yearly_cost_food', sa.Integer(), nullable=True),
    sa.Column('yearly_cost_iron', sa.Integer(), nullable=True),
    sa.Column('yearly_cost_timber', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('initiated_by_monarch_id', sa.Integer(), nullable=False),
    sa.Column('completed_by_monarch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_monarch_id'], ['person_db.id'], ),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_monarch_id'], ['person_db.id'], ),
    sa.ForeignKeyConstraint(['target_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['target_person_id'], ['person_db.id'], ),
    sa.ForeignKeyConstraint(['target_territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_dynasty_id'), ['dynasty_id'], unique=False)

    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_terrain', sa.Enum('PLAINS', 'HILLS', 'MOUNTAINS', 'FOREST', 'DESERT', 'TUNDRA', 'COASTAL', 'RIVER', 'LAKE', 'SWAMP', name='terraintype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_province_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_province_region_id'), ['region_id'], unique=False)

    op.create_table('settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('settlement_type', sa.String(length=50), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('trade_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_territory_id'), ['territory_id'], unique=False)

    op.create_table('territory_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('base_production', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('depletion_rate', sa.Float(), nullable=True),
    sa.Column('current_depletion', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('territory_id', 'resource_id', name='uix_territory_resource')
    )
    with op.batch_alter_table('territory_resource', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_territory_resource_territory_id'), ['territory_id'], unique=False)

    op.create_table('trade_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_dynasty_id', sa.Integer(), nullable=True),
    sa.Column('target_dynasty_id', sa.Integer(), nullable=True),
    sa.Column('source_territory_id', sa.Integer(), nullable=True),
    sa.Column('destination_territory_id', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.Enum('FOOD', 'TIMBER', 'STONE', 'IRON', 'GOLD', 'SPICES', 'WINE', 'SILK', 'JEWELRY', name='resourcetype'), nullable=True),
    sa.Column('resource_amount', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('profit_source', sa.Float(), nullable=True),
    sa.Column('profit_target', sa.Float(), nullable=True),
    sa.Column('trade_volume', sa.Integer(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('risk', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('established_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_territory_id'], ['territory.id'], ),
    sa.ForeignKeyConstraint(['source_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['source_territory_id'], ['territory.id'], ),
    sa.ForeignKeyConstraint(['target_dynasty_id'], ['dynasty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_route', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_route_destination_territory_id'), ['destination_territory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_route_source_dynasty_id'), ['source_dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_route_source_territory_id'), ['source_territory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_route_target_dynasty_id'), ['target_dynasty_id'], unique=False)

    op.create_table('war',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('defender_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('war_goal', sa.Enum('CONQUEST', 'VASSALIZE', 'INDEPENDENCE', 'TRIBUTE', 'HUMILIATE', 'RELIGIOUS', name='wargoal'), nullable=False),
    sa.Column('target_territory_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('attacker_war_score', sa.Integer(), nullable=True),
    sa.Column('defender_war_score', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['defender_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['target_territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('war', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_war_attacker_dynasty_id'), ['attacker_dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_war_defender_dynasty_id'), ['defender_dynasty_id'], unique=False)

    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('attacker_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('defender_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('attacker_army_id', sa.Integer(), nullable=True),
    sa.Column('defender_army_id', sa.Integer(), nullable=True),
    sa.Column('winner_dynasty_id', sa.Integer(), nullable=True),
    sa.Column('attacker_casualties', sa.Integer(), nullable=True),
    sa.Column('defender_casualties', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_army_id'], ['army.id'], ),
    sa.ForeignKeyConstraint(['attacker_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['defender_army_id'], ['army.id'], ),
    sa.ForeignKeyConstraint(['defender_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.ForeignKeyConstraint(['winner_dynasty_id'], ['dynasty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('battle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_battle_war_id'), ['war_id'], unique=False)

    op.create_table('military_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.Enum('LEVY_SPEARMEN', 'PROFESSIONAL_SWORDSMEN', 'ELITE_GUARDS', 'ARCHERS', 'LIGHT_CAVALRY', 'HEAVY_CAVALRY', 'HORSE_ARCHERS', 'KNIGHTS', 'BATTERING_RAM', 'SIEGE_TOWER', 'CATAPULT', 'TREBUCHET', 'TRANSPORT_SHIP', 'WAR_GALLEY', 'HEAVY_WARSHIP', 'FIRE_SHIP', name='unittype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('experience', sa.Float(), nullable=True),
    sa.Column('morale', sa.Float(), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.Column('commander_id', sa.Integer(), nullable=True),
    sa.Column('army_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_cost', sa.Integer(), nullable=False),
    sa.Column('food_consumption', sa.Float(), nullable=False),
    sa.Column('created_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['army_id'], ['army.id'], ),
    sa.ForeignKeyConstraint(['commander_id'], ['person_db.id'], ),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('military_unit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_military_unit_army_id'), ['army_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_dynasty_id'), ['dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_military_unit_territory_id'), ['territory_id'], unique=False)

    op.create_table('siege',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('attacker_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('defender_dynasty_id', sa.Integer(), nullable=False),
    sa.Column('attacker_army_id', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_army_id'], ['army.id'], ),
    sa.ForeignKeyConstraint(['attacker_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['defender_dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('siege', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siege_war_id'), ['war_id'], unique=False)

    op.create_table('treaty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diplomatic_relation_id', sa.Integer(), nullable=False),
    sa.Column('treaty_type', sa.Enum('NON_AGGRESSION', 'DEFENSIVE_ALLIANCE', 'MILITARY_ALLIANCE', 'VASSALAGE', 'TRADE_AGREEMENT', 'MARKET_ACCESS', 'RESOURCE_EXCHANGE', 'ECONOMIC_UNION', 'CULTURAL_EXCHANGE', 'ROYAL_MARRIAGE', name='treatytype'), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('terms_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diplomatic_relation_id'], ['diplomatic_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treaty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treaty_diplomatic_relation_id'), ['diplomatic_relation_id'], unique=False)

    op.create_table('history_log_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynasty_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('event_string', sa.Text(), nullable=False),
    sa.Column('person1_sim_id', sa.Integer(), nullable=True),
    sa.Column('person2_sim_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=True),
    sa.Column('war_id', sa.Integer(), nullable=True),
    sa.Column('battle_id', sa.Integer(), nullable=True),
    sa.Column('treaty_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battle.id'], ),
    sa.ForeignKeyConstraint(['dynasty_id'], ['dynasty.id'], ),
    sa.ForeignKeyConstraint(['person1_sim_id'], ['person_db.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person2_sim_id'], ['person_db.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ),
    sa.ForeignKeyConstraint(['treaty_id'], ['treaty.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history_log_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_log_entry_dynasty_id'), ['dynasty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_log_entry_year'), ['year'], unique=False)

    # Drop legacy ad-hoc version-tracking table if it exists (pre-Alembic deployments)
    from sqlalchemy import inspect as sa_inspect
    conn = op.get_bind()
    if sa_inspect(conn).has_table('db_version'):
        op.drop_table('db_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: db_version is not recreated on downgrade (it was a legacy artifact, not an ORM model)
    with op.batch_alter_table('history_log_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_log_entry_year'))
        batch_op.drop_index(batch_op.f('ix_history_log_entry_dynasty_id'))

    op.drop_table('history_log_entry')
    with op.batch_alter_table('treaty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treaty_diplomatic_relation_id'))

    op.drop_table('treaty')
    with op.batch_alter_table('siege', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siege_war_id'))

    op.drop_table('siege')
    with op.batch_alter_table('military_unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_military_unit_territory_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_dynasty_id'))
        batch_op.drop_index(batch_op.f('ix_military_unit_army_id'))

    op.drop_table('military_unit')
    with op.batch_alter_table('battle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_battle_war_id'))

    op.drop_table('battle')
    with op.batch_alter_table('war', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_war_defender_dynasty_id'))
        batch_op.drop_index(batch_op.f('ix_war_attacker_dynasty_id'))

    op.drop_table('war')
    with op.batch_alter_table('trade_route', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_route_target_dynasty_id'))
        batch_op.drop_index(batch_op.f('ix_trade_route_source_territory_id'))
        batch_op.drop_index(batch_op.f('ix_trade_route_source_dynasty_id'))
        batch_op.drop_index(batch_op.f('ix_trade_route_destination_territory_id'))

    op.drop_table('trade_route')
    with op.batch_alter_table('territory_resource', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territory_resource_territory_id'))

    op.drop_table('territory_resource')
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_territory_id'))

    op.drop_table('settlement')
    with op.batch_alter_table('province', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_province_region_id'))
        batch_op.drop_index(batch_op.f('ix_province_name'))

    op.drop_table('province')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_dynasty_id'))

    op.drop_table('project')
    with op.batch_alter_table('marriage_offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marriage_offer_target_dynasty_id'))
        batch_op.drop_index(batch_op.f('ix_marriage_offer_proposer_dynasty_id'))

    op.drop_table('marriage_offer')
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_dynasty_id'))

    op.drop_table('loan')
    with op.batch_alter_table('diplomatic_relation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diplomatic_relation_dynasty2_id'))
        batch_op.drop_index(batch_op.f('ix_diplomatic_relation_dynasty1_id'))

    op.drop_table('diplomatic_relation')
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_target_dynasty_id'))
        batch_op.drop_index(batch_op.f('ix_claim_source_dynasty_id'))
        batch_op.drop_index(batch_op.f('ix_claim_claimant_sim_id'))

    op.drop_table('claim')
    op.drop_table('chronicle_entry')
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_territory_id'))

    op.drop_table('building')
    with op.batch_alter_table('army', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_army_territory_id'))
        batch_op.drop_index(batch_op.f('ix_army_dynasty_id'))

    op.drop_table('army')
    op.drop_table('user_account')
    with op.batch_alter_table('territory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_territory_province_id'))
        batch_op.drop_index(batch_op.f('ix_territory_name'))
        batch_op.drop_index(batch_op.f('ix_territory_controller_dynasty_id'))

    op.drop_table('territory')
    op.drop_table('resource')
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_name'))

    op.drop_table('region')
    with op.batch_alter_table('person_db', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_db_dynasty_id'))

    op.drop_table('person_db')
    with op.batch_alter_table('dynasty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynasty_name'))

    op.drop_table('dynasty')
    # ### end Alembic commands ###
