# models/free_action_system.py
"""
Free Action system (Story 4-1).

Provides a single dispatcher, :class:`FreeActionSystem`, that performs an
out-of-turn ("free") action for a dynasty. Free actions do NOT tick the turn:
they never modify ``current_simulation_year``. Diplomatic actions delegate to
the existing :class:`DiplomacySystem` (we do not reimplement diplomacy here).

Every successful action appends a ``HistoryLogEntryDB`` with
``event_type='free_action'`` to the session (the route is responsible for
committing — this module never commits). The chronicle line is now *flavored*
(Story 4-2): a medieval-chronicler one-liner generated by the LLM when a key is
present, else a deterministic fallback. The flavor never affects ``event_type``.

Story 4-2 also adds reversible-action undo. After a successful *reversible*
action the dispatcher records ``self.last_undo_token`` — a snapshot of the
mutated DynastyDB fields plus the queued history-entry id — which the route
pushes onto a per-session undo stack. :meth:`undo_free_action` restores the
snapshot and deletes the history entry. Reversible: name_heir,
adopt_succession_law, hold_feast, hold_tournament, pardon_vassal. The four
diplomatic actions are non-reversible (token left ``None``).

Frozen contract (route + tests depend on these exact names):
    from models.free_action_system import FreeActionSystem, VALID_FREE_ACTIONS
    FreeActionSystem(session)
    perform_free_action(dynasty_id, action_type, params) -> (ok, message)
    undo_free_action(dynasty_id, undo_token) -> (ok, message)
    self.last_undo_token  (None or dict)
"""

import logging
import os
from typing import Optional, Tuple

from sqlalchemy.orm import Session

from models.db_models import (
    DynastyDB, PersonDB, HistoryLogEntryDB, TreatyType, WarGoal,
)
from models.diplomacy_system import DiplomacySystem
from utils.llm_prompts import (
    build_free_action_flavor_prompt,
    generate_free_action_flavor_fallback,
)

logger = logging.getLogger('royal_succession.free_action_system')


def _llm_available() -> bool:
    """Return True if the LLM API key is present in the running Flask app.

    Mirrors models/project_system.py:_llm_available(). Off in tests, so flavor
    falls back to the deterministic generator.
    """
    try:
        from flask import current_app
        return current_app.config.get('FLASK_APP_GOOGLE_API_KEY_PRESENT', False)
    except Exception:
        return False

# Frozen list of accepted free-action types.
VALID_FREE_ACTIONS = [
    'declare_war',
    'propose_treaty',
    'send_envoy',
    'issue_ultimatum',
    'name_heir',
    'adopt_succession_law',
    'hold_feast',
    'hold_tournament',
    'pardon_vassal',
]

# Accepted succession laws for the `adopt_succession_law` action.
VALID_SUCCESSION_LAWS = [
    'PRIMOGENITURE_MALE_PREFERENCE',
    'PRIMOGENITURE_ABSOLUTE',
    'ELECTIVE',
    'SENIORITY',
]


class FreeActionSystem:
    """Dispatches out-of-turn free actions for a dynasty."""

    def __init__(self, session: Session):
        self.session = session
        # Set after a successful *reversible* action; consumed by the route to
        # push onto the per-session undo stack. Non-reversible → stays None.
        self.last_undo_token = None

    # ------------------------------------------------------------------ #
    # Public dispatcher
    # ------------------------------------------------------------------ #
    def perform_free_action(
        self, dynasty_id: int, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        """
        Perform a free action.

        Args:
            dynasty_id: ID of the acting dynasty.
            action_type: One of ``VALID_FREE_ACTIONS``.
            params: Action-specific parameters.

        Returns:
            ``(ok, message)``.
        """
        params = params or {}
        self.last_undo_token = None

        if action_type not in VALID_FREE_ACTIONS:
            return False, f"Unknown free action: {action_type}"

        dynasty = self.session.get(DynastyDB, dynasty_id)
        if dynasty is None:
            return False, f"Dynasty {dynasty_id} not found"

        handler = {
            'declare_war': self._declare_war,
            'propose_treaty': self._propose_treaty,
            'send_envoy': self._diplomatic_action,
            'issue_ultimatum': self._diplomatic_action,
            'name_heir': self._name_heir,
            'adopt_succession_law': self._adopt_succession_law,
            'hold_feast': self._hold_feast,
            'hold_tournament': self._hold_tournament,
            'pardon_vassal': self._pardon_vassal,
        }[action_type]

        return handler(dynasty, action_type, params)

    # ------------------------------------------------------------------ #
    # Chronicle helper (AC4)
    # ------------------------------------------------------------------ #
    def _append_chronicle(
        self,
        dynasty: DynastyDB,
        action_type: str,
        target_name: Optional[str] = None,
    ) -> HistoryLogEntryDB:
        """Queue a flavored free-action history entry and return it.

        Story 4-2: ``event_string`` is now a medieval-chronicler one-liner —
        LLM-generated when a key is present, deterministic fallback otherwise.
        ``event_type`` stays ``'free_action'`` and ``year`` stays current.
        Does NOT commit. Returns the (unflushed) entry so reversible handlers
        can flush + capture its id.
        """
        event_string = self._build_flavor(dynasty, action_type, target_name)
        entry = HistoryLogEntryDB(
            dynasty_id=dynasty.id,
            year=dynasty.current_simulation_year,
            event_string=event_string,
            event_type='free_action',
        )
        self.session.add(entry)
        logger.info(
            "Free-action chronicle queued for dynasty %s (year %s): %s",
            dynasty.id, dynasty.current_simulation_year, event_string,
        )
        return entry

    # ------------------------------------------------------------------ #
    # Flavor (LLM-guarded, deterministic fallback)
    # ------------------------------------------------------------------ #
    def _current_monarch_name(self, dynasty: DynastyDB) -> str:
        """Name of the dynasty's living monarch, or 'the ruler' as fallback."""
        monarch = (
            self.session.query(PersonDB)
            .filter(
                PersonDB.dynasty_id == dynasty.id,
                PersonDB.is_monarch.is_(True),
                PersonDB.death_year.is_(None),
            )
            .first()
        )
        if monarch is None:
            return "the ruler"
        full = f"{monarch.name or ''} {monarch.surname or ''}".strip()
        return full or "the ruler"

    def _build_flavor(
        self,
        dynasty: DynastyDB,
        action_type: str,
        target_name: Optional[str],
    ) -> str:
        """Build the flavored chronicle line; any LLM failure → fallback."""
        monarch_name = self._current_monarch_name(dynasty)
        year = dynasty.current_simulation_year

        if _llm_available():
            try:
                import google.generativeai as genai
                from flask import current_app
                api_key = (
                    current_app.config.get("FLASK_APP_GOOGLE_API_KEY")
                    or os.environ.get("GOOGLE_API_KEY")
                )
                if api_key:
                    genai.configure(api_key=api_key)
                    model = genai.GenerativeModel("gemini-1.5-flash")
                    prompt = build_free_action_flavor_prompt(
                        action_type=action_type,
                        dynasty_name=dynasty.name,
                        monarch_name=monarch_name,
                        year=year,
                        target_name=target_name,
                    )
                    response = model.generate_content(
                        prompt,
                        generation_config={
                            "max_output_tokens": 150,
                            "temperature": 0.8,
                        },
                    )
                    text = response.text.strip() if response.text else ""
                    if text:
                        return text
            except Exception as llm_exc:
                logger.warning(
                    "LLM flavor for free action %r failed (dynasty %s): %s",
                    action_type, dynasty.id, llm_exc,
                )

        return generate_free_action_flavor_fallback(
            action_type=action_type,
            dynasty_name=dynasty.name,
            monarch_name=monarch_name,
            year=year,
            target_name=target_name,
        )

    # ------------------------------------------------------------------ #
    # Undo-token capture (reversible actions only)
    # ------------------------------------------------------------------ #
    def _capture_undo_token(
        self,
        dynasty: DynastyDB,
        action_type: str,
        snapshot: dict,
        entry: HistoryLogEntryDB,
    ) -> None:
        """Flush to assign the entry id, then record self.last_undo_token.

        flush, NOT commit — the route owns the commit. The snapshot holds the
        *prior* field values (captured before mutation by the handler).
        """
        self.session.flush()
        self.last_undo_token = {
            "action_type": action_type,
            "dynasty_id": dynasty.id,
            "snapshot": snapshot,
            "history_entry_id": entry.id,
        }

    # ------------------------------------------------------------------ #
    # Undo (Story 4-2)
    # ------------------------------------------------------------------ #
    def undo_free_action(
        self, dynasty_id: int, undo_token: dict
    ) -> Tuple[bool, str]:
        """Reverse a previously-performed reversible free action.

        Restores each snapshotted DynastyDB field and deletes the action's
        history entry (if still present). Never commits; never touches
        ``current_simulation_year``. Bad/foreign token → ``(False, "Nothing
        to undo")``.
        """
        if not isinstance(undo_token, dict):
            return False, "Nothing to undo"
        if undo_token.get("dynasty_id") != dynasty_id:
            return False, "Nothing to undo"

        dynasty = self.session.get(DynastyDB, dynasty_id)
        if dynasty is None:
            return False, "Nothing to undo"

        snapshot = undo_token.get("snapshot") or {}
        for field, prior_value in snapshot.items():
            setattr(dynasty, field, prior_value)

        entry_id = undo_token.get("history_entry_id")
        if entry_id is not None:
            entry = self.session.get(HistoryLogEntryDB, entry_id)
            if entry is not None:
                self.session.delete(entry)

        action_type = undo_token.get("action_type", "action")
        logger.info(
            "Undid free action %r for dynasty %s (restored %s)",
            action_type, dynasty_id, list(snapshot.keys()),
        )
        return True, f"Undid {action_type}."

    # ------------------------------------------------------------------ #
    # Diplomatic actions — delegate to DiplomacySystem
    # ------------------------------------------------------------------ #
    def _declare_war(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        target_id = params.get('target_dynasty_id')
        if target_id is None:
            return False, "declare_war requires 'target_dynasty_id'"

        diplomacy = DiplomacySystem(self.session)
        result = diplomacy.declare_war(
            attacker_dynasty_id=dynasty.id,
            defender_dynasty_id=target_id,
            war_goal=WarGoal.HUMILIATE,
        )
        ok, message = self._normalize(result)
        if ok:
            self._append_chronicle(
                dynasty, action_type,
                target_name=self._target_dynasty_name(target_id),
            )
        return ok, message

    def _propose_treaty(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        target_id = params.get('target_dynasty_id')
        if target_id is None:
            return False, "propose_treaty requires 'target_dynasty_id'"

        treaty_type = self._resolve_treaty_type(params.get('treaty_type'))

        diplomacy = DiplomacySystem(self.session)
        result = diplomacy.create_treaty(
            dynasty1_id=dynasty.id,
            dynasty2_id=target_id,
            treaty_type=treaty_type,
        )
        ok, message = self._normalize(result)
        if ok:
            self._append_chronicle(
                dynasty, action_type,
                target_name=self._target_dynasty_name(target_id),
            )
        return ok, message

    def _diplomatic_action(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        """Handles send_envoy and issue_ultimatum."""
        target_id = params.get('target_dynasty_id')
        if target_id is None:
            return False, f"{action_type} requires 'target_dynasty_id'"

        diplomacy = DiplomacySystem(self.session)
        result = diplomacy.perform_diplomatic_action(
            actor_dynasty_id=dynasty.id,
            target_dynasty_id=target_id,
            action_type=action_type,
        )
        ok, message = self._normalize(result)
        if ok:
            self._append_chronicle(
                dynasty, action_type,
                target_name=self._target_dynasty_name(target_id),
            )
        return ok, message

    # ------------------------------------------------------------------ #
    # Succession actions
    # ------------------------------------------------------------------ #
    def _name_heir(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        heir_id = params.get('heir_person_id')
        if heir_id is None:
            return False, "name_heir requires 'heir_person_id'"

        heir = self.session.get(PersonDB, heir_id)
        if heir is None:
            return False, f"Person {heir_id} not found"
        if heir.dynasty_id != dynasty.id:
            return False, f"Person {heir_id} does not belong to dynasty {dynasty.id}"
        if heir.death_year is not None:
            return False, f"Person {heir_id} is deceased and cannot be named heir"

        snapshot = {'designated_heir_id': dynasty.designated_heir_id}
        dynasty.designated_heir_id = heir.id
        entry = self._append_chronicle(
            dynasty, action_type,
            target_name=heir.name,
        )
        self._capture_undo_token(dynasty, action_type, snapshot, entry)
        return True, f"{heir.name} has been named heir."

    def _adopt_succession_law(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        law = params.get('law')
        if law is None:
            return False, "adopt_succession_law requires 'law'"
        if law not in VALID_SUCCESSION_LAWS:
            return False, f"Invalid succession law: {law}"

        snapshot = {'succession_law': dynasty.succession_law}
        dynasty.succession_law = law
        entry = self._append_chronicle(dynasty, action_type)
        self._capture_undo_token(dynasty, action_type, snapshot, entry)
        return True, f"Succession law set to {law}."

    # ------------------------------------------------------------------ #
    # Court / prestige actions
    # ------------------------------------------------------------------ #
    def _hold_feast(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        cost = 30
        if dynasty.current_wealth < cost:
            return False, f"Cannot afford feast (need {cost} gold)"

        snapshot = {
            'current_wealth': dynasty.current_wealth,
            'prestige': dynasty.prestige,
        }
        dynasty.current_wealth -= cost
        dynasty.prestige = (dynasty.prestige or 0) + 5
        entry = self._append_chronicle(dynasty, action_type)
        self._capture_undo_token(dynasty, action_type, snapshot, entry)
        return True, "A grand feast was held (+5 prestige)."

    def _hold_tournament(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        cost = 50
        if dynasty.current_wealth < cost:
            return False, f"Cannot afford tournament (need {cost} gold)"

        snapshot = {
            'current_wealth': dynasty.current_wealth,
            'prestige': dynasty.prestige,
        }
        dynasty.current_wealth -= cost
        dynasty.prestige = (dynasty.prestige or 0) + 10
        entry = self._append_chronicle(dynasty, action_type)
        self._capture_undo_token(dynasty, action_type, snapshot, entry)
        return True, "A grand tournament was held (+10 prestige)."

    def _pardon_vassal(
        self, dynasty: DynastyDB, action_type: str, params: dict
    ) -> Tuple[bool, str]:
        snapshot = {'honor': dynasty.honor}
        dynasty.honor = min(100, (dynasty.honor or 0) + 5)
        entry = self._append_chronicle(dynasty, action_type)
        self._capture_undo_token(dynasty, action_type, snapshot, entry)
        return True, "A vassal was pardoned (+5 honor)."

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #
    def _target_dynasty_name(self, target_id) -> Optional[str]:
        """Resolve a target dynasty's name for chronicle flavor, or None."""
        if target_id is None:
            return None
        target = self.session.get(DynastyDB, target_id)
        if target is not None and target.name:
            return f"House {target.name}"
        return f"dynasty {target_id}"

    @staticmethod
    def _normalize(result) -> Tuple[bool, str]:
        """Normalize ``(ok, msg)`` or ``(ok, msg, obj)`` to ``(ok, msg)``."""
        ok = bool(result[0])
        message = result[1] if len(result) > 1 else ""
        return ok, message

    @staticmethod
    def _resolve_treaty_type(raw) -> TreatyType:
        """Resolve a treaty type from params, defaulting to NON_AGGRESSION."""
        if isinstance(raw, TreatyType):
            return raw
        if isinstance(raw, str):
            # Accept either the enum name or the enum value.
            by_name = getattr(TreatyType, raw.upper(), None)
            if isinstance(by_name, TreatyType):
                return by_name
            for member in TreatyType:
                if member.value == raw:
                    return member
        return TreatyType.NON_AGGRESSION
